### ISSUE TITLE
Cold open

### ISSUE THREAD

**Issue by happykitt3n** [michaelbull/vlc-credit-skipper#3]
Most shows have a cold open, theres no way anyone could use this if we can't specify the start and end point within each file.

**Comment by michaelbull** [comment]
What do you mean by a 'cold open'?

>theres no way anyone could use this

The [example gif](https://cn.opendesktop.org/img/e/a/6/6/3e6a6ba746ab3d9c278810537f847ae41e87.gif) shows how it can be used for shows that have a consistent start/end credit length, myself and others use it a lot with this setup.

**Comment by michaelbull** [comment]
After some Googling it appears that a 'cold open' seems to imply the following video structure:

1. Cold open
2. Intro
3. Video
4. Outro

I think to support this, we would need to need to effectively split up each `child` when [iterating the playlist children](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L143) in order to represent the 'cold open' as a separate child, upon which we call [`enqueue`](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L156). 

We'd then start the video at the timestamp calculated by `the cold open duration` + `the intro duration`, and enqueue it as we already do.

@happykitt3n would you like to submit a PR for this change?

**Comment by Trevelopment** [comment]
@happykitt3n Try this addon I developed that takes a cold open into account [VLC Super Skipper](https://github.com/Trevelopment/vlc-super-skipper)
